//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AnungooODataService.Anungoo
{

    public partial class Test : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fTest1;
        public string Test1
        {
            get { return fTest1; }
            set { SetPropertyValue<string>("Test1", ref fTest1, value); }
        }
        string fTest2;
        public string Test2
        {
            get { return fTest2; }
            set { SetPropertyValue<string>("Test2", ref fTest2, value); }
        }
        string fTest3;
        public string Test3
        {
            get { return fTest3; }
            set { SetPropertyValue<string>("Test3", ref fTest3, value); }
        }
    }

}
